### ISSUE TITLE
Rails 4.2.1 NameError: constant not defined 

### ISSUE THREAD

**Issue by arielvalentin** [Casecommons/with_model#22]
After upgrading to Rails 4.2.1 we are experiencing the following error:

```
An error occurred in an after hook
    NameError: constant Object::Presenter not defined
    occurred at /Users/foo/.rvm/gems/ruby-2.1.5@foo-rails4/gems/with_model-1.2.1/lib/with_model/constant_stubber.rb:18:in `remove_const'
```

I haven't had a chance to look into the root cause of this issue but wanted to bring it to your attention right away.

**Comment by amarshall** [comment]
Can you provide a minimal example that shows this error? Otherwise we have no way to debug it.

**Comment by arielvalentin** [comment]
FYI. After upgrading to 4.2.3; this error went away. Perhaps an issue with AR?
