### ISSUE TITLE
Maybe, release?

### ISSUE THREAD

**Issue by palkan** [Casecommons/with_model#29]
Hey there!

Any plans on releasing a new version? The latest release is not compatible with Rails 6 and `master` is https://github.com/Casecommons/with_model/pull/28.

**Comment by pockata-kt** [comment]
Please, release this. I'm having trouble upgrading to rails 6.0 because of this.

**Comment by KevinBongart** [comment]
What's preventing Rails 6 support? How can I help? cc @amarshall

**Comment by palkan** [comment]
> What's preventing Rails 6 support? 

Rails 6 is supported in master; all we need is release)

**Comment by amarshall** [comment]
ActiveRecord 6.0 wasn’t really supported, just the gemspec had been bumped to allow for development. In fact, the test suite had failures related to resetting ActiveSupport’s descendant tracking. Anyway, I’ve fixed the failures by working around their new API a bit (oy), and have released v2.1.3 which supports ActiveRecord 6.0.
